### ISSUE TITLE
Parameter is not valid

### ISSUE THREAD

**Issue by liuatgit** [liuziangexit/HEIF-Utility#5]
invoke_dll.invoke_heif_to_jpg works great on most heic files, however a few files return exception "Parameter is not valid".

**Comment by liuziangexit** [comment]
give me example files pls

**Comment by liuatgit** [comment]
sent by email

**Comment by liuziangexit** [comment]
I can reproduce the problem.i will handle that, thanks for report. when bug fixed, i will notify you.

**Comment by liuziangexit** [comment]
What is the probability of occurrence of this problem?

**Comment by dengxinghai89** [comment]
I also encountered the same problem, and the "I n_1440x960. Heic" in "heif-utility-native-dll-master\test" would have such a situation.

**Comment by dengxinghai89** [comment]
下载HEIF-Utility-Native-DLL-master.zip, 再”HEIF-Utility-Native-DLL-master\test”目录下有多个.heic文件。其中alpha_1440x960.heic，autumn_1440x960.heic，cheers_1440x960.heic会出现问题。heif2jpg返回的output_buffer格式损坏。

**Comment by liuziangexit** [comment]
@dengxinghai89 你遇到的问题是正常情况。你提到的那几个文件名我很熟，因为那是诺基亚网站提供的demo文件。我的软件只支持 Apple HEIF，而不支持普通的 Single Image HEIF，所以打不开是正常的，我在readme里写的很清楚了。

**Comment by liuziangexit** [comment]
实际上我已经搞明白liuatgit提出的问题的原因所在了。是诺基亚的代码的问题。hevcimagefilereader::initialize抛出了std::out_of_range的异常。是因为一个std::map里面找不到对应的键。但为什么会这样我依然不清楚，但我在尝试修复。这是一个小概率事件。

In fact, I know the reason of liuatgit’s question. Is a bug of Nokia's code. hevcimagefilereader :: initialize throws an exception std :: out_of_range. Because a std::map can not find key. i dont know why it happend,but i will try to fix it.This is a small probability bug.

**Comment by liuziangexit** [comment]
bug fixed, HEIF Utility Release 3 now available.

**Comment by liuziangexit** [comment]
@liuatgit Thank you for your help.Without your report and example files, i can't fix it.
